import { cp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(await readFile(resolve(root,'package.json'),'utf8'));
const name = `QuotaDesk-v${version}-macos-${process.arch}`;
const out = resolve(root,'dist/release');
const folder = resolve(out,name);
await rm(folder,{recursive:true,force:true});
await mkdir(folder,{recursive:true});
await cp(resolve(out,'Quota Desk.app'),resolve(folder,'Quota Desk.app'),{recursive:true});
for (const file of ['README.md','LICENSE','THIRD_PARTY_NOTICES.md']) await cp(resolve(root,file),resolve(folder,file));
await writeFile(resolve(folder,'BUILD.json'),JSON.stringify({version,architecture:process.arch,node:process.version,minimumMacOS:'13.0',signing:'ad-hoc',notarized:false},null,2)+'\n');
const zip=resolve(out,name+'.zip');
await rm(zip,{force:true});
execFileSync('/usr/bin/ditto',['-c','-k','--norsrc','--noextattr','--keepParent',folder,zip]);
const hash=createHash('sha256').update(await readFile(zip)).digest('hex');
await writeFile(resolve(out,'SHA256SUMS'),`${hash}  ${name}.zip\n`);
console.log(`Created ${zip}`);
